### ISSUE TITLE
"squish" is not exported by the Mojo::Util module

### ISSUE THREAD

**Issue by eserte** [Csson/p5-test-mojo-trim#2]
My smokers started to report fails, probably because of Mojolicious 7.
Sample report: http://www.cpantesters.org/cpan/report/71314ca4-4e40-11e6-9c90-eb5010d7a009

**Comment by eserte** [comment]
Probably relevant change: https://metacpan.org/source/SRI/Mojolicious-7.0/Changes#L7

**Comment by Csson** [comment]
Thanks! Fixed in 0.1000.
